/**
 * InvestScape™ E86 Phase 7 — Government & Public Data Source Inventory.
 * © 2026 Lighthouse Research Ltd. All rights reserved.
 *
 * Research-only classification metadata (Parts 2, 3, 10, 12 of the Phase 7
 * specification). No numeric CRE benchmark values live in this file — only
 * enums, URLs, dates, and descriptive notes about what each source publishes
 * and under what terms. See docs/E86-phase7-government-public-api-ingestion.md
 * for the full narrative report and additional citations.
 *
 * IMPORTANT: "publicly accessible" is not "freely redistributable." A source
 * with `apiAvailability: "public_api"` and `pricingModel: "free"` can still
 * have `redistributionRestriction: "unclear"` — those are different axes.
 * `legallyIncorporable: null` means the terms were read but genuinely do not
 * resolve the question; treat it as REQUIRES LICENSE REVIEW, not as "no."
 */
import type { CREPublicSourceProfile } from "./types";

export const CRE_PUBLIC_SOURCE_REGISTRY: readonly CREPublicSourceProfile[] = [
  // ---------------------------------------------------------------- CANADA
  {
    sourceId: "statcan-wds",
    officialName: "Statistics Canada",
    country: "CA",
    jurisdiction: "Federal",
    datasetOrApiName: "Web Data Service (WDS) — Table 18-10-0135-01 Building Construction Price Indexes",
    categories: ["direct_cre_benchmark", "cre_adjacent_economic"],
    url: "https://www.statcan.gc.ca/en/developers/wds",
    apiAvailability: "public_api",
    downloadFormats: ["JSON", "CSV", "SDMX"],
    authRequirement: "none",
    pricingModel: "free",
    rateLimitNote: "No published numeric quota found as of 2026-09-11; WDS documentation recommends bulk/vector-based retrieval rather than per-cell polling for large jobs.",
    commercialUseRestriction: "permitted",
    redistributionRestriction: "permitted",
    attributionRequired: true,
    updateFrequency: "quarterly",
    geographicGranularity: "metro_cbsa",
    historicalDepthNote: "Table 18-10-0135-01 series extend back multiple decades; exact start varies by census metropolitan area (CMA).",
    legallyIncorporable: true,
    licenseTags: ["PUBLIC_GOVERNMENT", "PUBLIC_API", "PUBLIC_DOWNLOAD", "ATTRIBUTION_REQUIRED", "COMMERCIAL_USE_PERMITTED"],
    refresh: {
      lastKnownPublicationPeriod: "Q2 2026 (per E86's existing statcan-bcpi registry entry)",
      retrievalMechanism: "WDS REST API (getDataFromCubePidCoordAndLatestNPeriods / getFullTableDownloadCSV)",
      historicalBackfillPossible: true,
      automatedIngestionSafe: true,
    },
    citiesCoveredVerified: ["Vancouver", "Calgary", "Edmonton", "Winnipeg", "Toronto", "Ottawa", "Montreal", "Halifax"],
    evidenceUrls: [
      "https://www.statcan.gc.ca/en/developers/wds",
      "https://www23.statcan.gc.ca/imdb-bmdi/pub/2317-eng.htm",
      "https://www.statcan.gc.ca/en/reference/licence",
    ],
    dateVerified: "2026-09-11",
    notes: "Statistics Canada's Open Licence (statcan.gc.ca/en/reference/licence) permits commercial use, modification and redistribution with attribution to Statistics Canada; this is the strongest redistribution posture of any source in this inventory. BCPI is a contractor-price index, not a direct cap-rate or $/SF benchmark — E86 already uses it only for escalation. Victoria and St. John's are not separately identified CMAs in the CMA-level BCPI table; national/regional series may exist at coarser granularity only (GEOGRAPHY_NOT_COVERED / GRANULARITY_NOT_AVAILABLE risk for those two cities, not verified as covered).",
  },
  {
    sourceId: "cmhc-hmip",
    officialName: "Canada Mortgage and Housing Corporation (CMHC)",
    country: "CA",
    jurisdiction: "Federal",
    datasetOrApiName: "Housing Market Information Portal",
    categories: ["rental_housing", "cre_adjacent_economic", "construction_permit"],
    url: "https://www.cmhc-schl.gc.ca/professionals/housing-markets-data-and-research/housing-data/data-tables",
    apiAvailability: "public_download",
    downloadFormats: ["CSV", "XLSX", "HTML tables"],
    authRequirement: "none",
    pricingModel: "free",
    commercialUseRestriction: "unclear",
    redistributionRestriction: "unclear",
    attributionRequired: true,
    updateFrequency: "monthly",
    geographicGranularity: "city_municipal",
    historicalDepthNote: "Rental Market Survey and Starts & Completions Survey historical series extend back decades for CMAs; portal does not document a general-purpose REST API (no key-based query interface found as of 2026-09-11).",
    legallyIncorporable: null,
    licenseTags: ["PUBLIC_GOVERNMENT", "PUBLIC_DOWNLOAD", "REDISTRIBUTION_UNCLEAR", "ATTRIBUTION_REQUIRED"],
    refresh: {
      retrievalMechanism: "Manual/scripted download of published table exports (no documented public API)",
      historicalBackfillPossible: true,
      automatedIngestionSafe: false,
    },
    citiesCoveredVerified: [],
    evidenceUrls: ["https://www.cmhc-schl.gc.ca/professionals/housing-markets-data-and-research/housing-data/data-tables"],
    dateVerified: "2026-09-11",
    notes: "Residential rental-market and housing-starts data (rental vacancy, average rents, starts/completions by structure type). Does NOT publish commercial cap rates. Already registered in CRE_SOURCE_REGISTRY as `cmhc-housing`; no automated adapter implemented in Phase 7 because no documented public API endpoint was found — marked API_OR_DOWNLOAD_UNAVAILABLE for automation purposes even though the data itself is a public download.",
  },
  {
    sourceId: "bc-assessment",
    officialName: "BC Assessment",
    country: "CA",
    jurisdiction: "British Columbia (provincial Crown corporation)",
    datasetOrApiName: "BC Assessment property value lookup / Assessment Search",
    categories: ["property_assessment"],
    url: "https://www.bcassessment.ca/",
    apiAvailability: "public_report_only",
    downloadFormats: ["Web lookup only"],
    authRequirement: "none",
    pricingModel: "free",
    commercialUseRestriction: "restricted",
    redistributionRestriction: "restricted",
    attributionRequired: true,
    updateFrequency: "annual",
    geographicGranularity: "parcel",
    historicalDepthNote: "Current assessment roll plus limited prior-year comparison per property; no documented bulk historical API for general public users.",
    legallyIncorporable: false,
    licenseTags: ["PUBLIC_GOVERNMENT", "COMMERCIAL_USE_UNCLEAR", "REDISTRIBUTION_UNCLEAR", "LICENSE_REQUIRED"],
    refresh: {
      retrievalMechanism: "Bulk data products available only via BC Assessment's commercial data-licensing program, not a public self-serve API.",
      historicalBackfillPossible: false,
      automatedIngestionSafe: false,
    },
    citiesCoveredVerified: [],
    evidenceUrls: ["https://www.bcassessment.ca/", "https://www.bcassessment.ca/about-us/data-advice-and-analytics"],
    dateVerified: "2026-09-11",
    notes: "Per-property lookup on the public site is for individual assessment values, not a scrapeable dataset; BC Assessment separately sells bulk assessment-roll data products under commercial terms (\"Data Advice and Analytics\"). Property assessments are administrative valuations set for taxation, not market cap rates or transaction prices, and must never be treated as either. REQUIRES LICENSE REVIEW for any bulk/automated use.",
  },
  {
    sourceId: "open-canada",
    officialName: "Government of Canada Open Data",
    country: "CA",
    jurisdiction: "Federal",
    datasetOrApiName: "open.canada.ca Open Government Portal (CKAN)",
    categories: ["cre_adjacent_economic", "demographic", "construction_permit", "not_available"],
    url: "https://open.canada.ca/en/open-data",
    apiAvailability: "public_api",
    downloadFormats: ["CSV", "JSON", "XML", "via CKAN API"],
    authRequirement: "none",
    pricingModel: "free",
    commercialUseRestriction: "permitted",
    redistributionRestriction: "permitted",
    attributionRequired: true,
    updateFrequency: "irregular",
    geographicGranularity: "city_municipal",
    historicalDepthNote: "Varies per dataset; the portal aggregates federal-department datasets rather than publishing a single time series.",
    legallyIncorporable: true,
    licenseTags: ["PUBLIC_GOVERNMENT", "PUBLIC_API", "PUBLIC_DOWNLOAD", "ATTRIBUTION_REQUIRED", "COMMERCIAL_USE_PERMITTED"],
    refresh: {
      retrievalMechanism: "CKAN REST API against the open.canada.ca registry",
      historicalBackfillPossible: true,
      automatedIngestionSafe: true,
    },
    citiesCoveredVerified: [],
    evidenceUrls: ["https://open.canada.ca/en/open-data", "https://open.canada.ca/en/open-government-licence-canada"],
    dateVerified: "2026-09-11",
    notes: "A portal/index, not a single dataset — published under the Open Government Licence – Canada, which explicitly permits commercial use and redistribution with attribution. No direct CRE cap-rate dataset was found through it; it is a routing layer to the same StatCan/CMHC/departmental data already assessed individually. Category recorded as `not_available` for direct CRE benchmarks specifically.",
  },
  {
    sourceId: "toronto-open-data",
    officialName: "City of Toronto",
    country: "CA",
    jurisdiction: "Toronto, ON (municipal)",
    datasetOrApiName: "Toronto Open Data Portal — Building Permits / Property Data",
    categories: ["construction_permit", "property_assessment"],
    url: "https://open.toronto.ca/",
    apiAvailability: "public_api",
    downloadFormats: ["CSV", "JSON", "GeoJSON via CKAN API"],
    authRequirement: "none",
    pricingModel: "free",
    commercialUseRestriction: "permitted",
    redistributionRestriction: "permitted",
    attributionRequired: true,
    updateFrequency: "irregular",
    geographicGranularity: "city_municipal",
    historicalDepthNote: "Permit datasets typically cover a rolling multi-year window; exact depth varies by dataset and was not individually verified per table in this phase.",
    legallyIncorporable: true,
    licenseTags: ["PUBLIC_GOVERNMENT", "PUBLIC_API", "PUBLIC_DOWNLOAD", "ATTRIBUTION_REQUIRED", "COMMERCIAL_USE_PERMITTED"],
    refresh: {
      retrievalMechanism: "CKAN API (open.toronto.ca uses the same platform as open.canada.ca)",
      historicalBackfillPossible: true,
      automatedIngestionSafe: true,
    },
    citiesCoveredVerified: ["Toronto"],
    evidenceUrls: ["https://open.toronto.ca/", "https://open.toronto.ca/open-data-licence/"],
    dateVerified: "2026-09-11",
    notes: "Building-permit counts/values are construction-activity indicators, not cap rates or $/SF construction costs. Representative example only; other E86 priority Canadian cities (Vancouver, Calgary, Edmonton, Winnipeg, Ottawa, Montreal, Halifax, St. John's, Victoria) each run separate municipal open-data portals under their own terms, not individually inventoried here — treat as GEOGRAPHY_NOT_COVERED per-city until each is checked.",
  },

  // ------------------------------------------------------------------- USA
  {
    sourceId: "fred-api",
    officialName: "Federal Reserve Bank of St. Louis",
    country: "US",
    jurisdiction: "Federal (regional Federal Reserve Bank)",
    datasetOrApiName: "FRED (Federal Reserve Economic Data) API",
    categories: ["cre_adjacent_economic"],
    url: "https://fred.stlouisfed.org/docs/api/fred/",
    apiAvailability: "public_api",
    downloadFormats: ["JSON", "XML"],
    authRequirement: "free_api_key",
    pricingModel: "free",
    rateLimitNote: "FRED documents an API key requirement (fred.stlouisfed.org/docs/api/api_key.html) and a Terms of Use page; a specific numeric rate-limit ceiling was not confirmed in this phase's research and should be re-checked against the live Terms of Use before high-volume automated use.",
    commercialUseRestriction: "unclear",
    redistributionRestriction: "unclear",
    attributionRequired: true,
    updateFrequency: "daily",
    geographicGranularity: "metro_cbsa",
    historicalDepthNote: "Most series (e.g. 30-Year Fixed Rate Mortgage Average, regional CPI, metro-level unemployment) run for decades; per-series depth varies and must be read from each series' own metadata.",
    legallyIncorporable: null,
    licenseTags: ["PUBLIC_GOVERNMENT", "PUBLIC_API", "ATTRIBUTION_REQUIRED", "COMMERCIAL_USE_UNCLEAR", "REDISTRIBUTION_UNCLEAR"],
    refresh: {
      retrievalMechanism: "FRED REST API (fred/series/observations endpoint)",
      historicalBackfillPossible: true,
      automatedIngestionSafe: true,
    },
    citiesCoveredVerified: ["Austin", "Houston", "Miami", "Seattle", "Phoenix"],
    evidenceUrls: ["https://fred.stlouisfed.org/docs/api/fred/", "https://fred.stlouisfed.org/docs/api/terms_of_use.html"],
    dateVerified: "2026-09-11",
    notes: "FRED itself republishes data originally produced by other agencies (BLS, Census, private compilers like Zillow for some series) — the underlying-producer distinction matters for citation (see CRECitation.underlyingDataProvider) and was the exact failure mode of the discredited Phase 4 Miami/Seattle cap-rate figures. FRED has NEVER published a commercial cap rate for any metro; E86's Phase 7 FRED adapter (adapters/fred-adapter.ts) is restricted by construction to producing `EconomicIndicatorObservation`s (category cre_adjacent_economic), which cannot satisfy the `CREObservation` cap_rate type. Full commercial-use/redistribution terms require reading the linked Terms of Use in detail; marked REQUIRES LICENSE REVIEW pending that.",
  },
  {
    sourceId: "us-census-api",
    officialName: "U.S. Census Bureau",
    country: "US",
    jurisdiction: "Federal",
    datasetOrApiName: "Census Data API (American Community Survey, Building Permits Survey)",
    categories: ["demographic", "construction_permit", "cre_adjacent_economic"],
    url: "https://www.census.gov/data/developers/data-sets.html",
    apiAvailability: "public_api",
    downloadFormats: ["JSON", "CSV"],
    authRequirement: "free_api_key",
    pricingModel: "free",
    rateLimitNote: "Terms of Service state usage 'may be subject to certain limitations on access, calls, or use' without a published numeric ceiling as of 2026-09-11.",
    commercialUseRestriction: "permitted",
    redistributionRestriction: "restricted",
    attributionRequired: true,
    updateFrequency: "annual",
    geographicGranularity: "metro_cbsa",
    historicalDepthNote: "ACS 5-year estimates available for most metro/place geographies going back to the mid-2000s vintage; 1-year estimates only for larger geographies.",
    legallyIncorporable: true,
    licenseTags: ["PUBLIC_GOVERNMENT", "PUBLIC_API", "ATTRIBUTION_REQUIRED", "COMMERCIAL_USE_PERMITTED"],
    refresh: {
      lastKnownPublicationPeriod: "ACS 2024 5-Year Estimates (most recent vintage confirmed generally available as of research date)",
      retrievalMechanism: "Census Data API (api.census.gov/data/<year>/acs/acs5)",
      historicalBackfillPossible: true,
      automatedIngestionSafe: true,
    },
    citiesCoveredVerified: ["Austin", "Houston", "Miami", "Seattle", "Phoenix"],
    evidenceUrls: [
      "https://www.census.gov/data/developers/data-sets.html",
      "https://www.census.gov/data/developers/about/terms-of-service.html",
    ],
    dateVerified: "2026-09-11",
    notes: "Data is public domain (17 U.S.C. §105) and commercial use is permitted; the Terms of Service prohibit publishing Census data 'in a manner that identifies any individual person, household, business or other entity' — a disclosure-avoidance rule, not a blanket redistribution ban, but flagged `restricted` here because it constrains HOW aggregate data may be combined/published rather than clearing all redistribution. Required attribution notice: \"This product uses the Census Bureau Data API but is not endorsed or certified by the Census Bureau.\" Population/employment/income are category (5)/(2) data, never a substitute for a CRE benchmark.",
  },
  {
    sourceId: "bea-api",
    officialName: "U.S. Bureau of Economic Analysis (BEA)",
    country: "US",
    jurisdiction: "Federal",
    datasetOrApiName: "BEA Data API (Regional GDP by MSA)",
    categories: ["cre_adjacent_economic"],
    url: "https://apps.bea.gov/API/signup/",
    apiAvailability: "public_api",
    downloadFormats: ["JSON", "XML"],
    authRequirement: "free_api_key",
    pricingModel: "free",
    commercialUseRestriction: "permitted",
    redistributionRestriction: "permitted",
    attributionRequired: true,
    updateFrequency: "annual",
    geographicGranularity: "metro_cbsa",
    historicalDepthNote: "Regional GDP-by-MSA series generally available from the late 1990s/2000s onward depending on the table.",
    legallyIncorporable: true,
    licenseTags: ["PUBLIC_GOVERNMENT", "PUBLIC_API", "ATTRIBUTION_REQUIRED", "COMMERCIAL_USE_PERMITTED"],
    refresh: {
      retrievalMechanism: "BEA REST/JSON API",
      historicalBackfillPossible: true,
      automatedIngestionSafe: true,
    },
    citiesCoveredVerified: [],
    evidenceUrls: ["https://apps.bea.gov/API/signup/", "https://www.bea.gov/help/faq/1163"],
    dateVerified: "2026-09-11",
    notes: "Publishes metro-area GDP and personal income, both economic-activity context, not CRE benchmarks. Not implemented as an adapter in Phase 7 (deferred — see docs Part 10) but architecturally supported by the same generic SourceAdapter contract as FRED/Census.",
  },
  {
    sourceId: "bls-api",
    officialName: "U.S. Bureau of Labor Statistics (BLS)",
    country: "US",
    jurisdiction: "Federal",
    datasetOrApiName: "BLS Public Data API (CES employment, PPI construction)",
    categories: ["cre_adjacent_economic"],
    url: "https://www.bls.gov/developers/",
    apiAvailability: "public_api",
    downloadFormats: ["JSON"],
    authRequirement: "free_api_key",
    pricingModel: "free",
    rateLimitNote: "Documented tiers: unregistered access is more limited (25 queries/day, 25 years of data per query per BLS developer docs) vs. a registered API key (500 queries/day, 20 years per query) — re-verify exact figures against the live BLS developer page before relying on them operationally.",
    commercialUseRestriction: "permitted",
    redistributionRestriction: "permitted",
    attributionRequired: true,
    updateFrequency: "monthly",
    geographicGranularity: "metro_cbsa",
    historicalDepthNote: "PPI construction series and metro-area CES employment series generally run back decades at the national level; metro-level series availability and depth vary by series.",
    legallyIncorporable: true,
    licenseTags: ["PUBLIC_GOVERNMENT", "PUBLIC_API", "ATTRIBUTION_REQUIRED", "COMMERCIAL_USE_PERMITTED"],
    refresh: {
      retrievalMechanism: "BLS Public Data API v2 (POST to api.bls.gov/publicAPI/v2/timeseries/data)",
      historicalBackfillPossible: true,
      automatedIngestionSafe: true,
    },
    citiesCoveredVerified: [],
    evidenceUrls: ["https://www.bls.gov/developers/", "https://www.bls.gov/bls/data_index.htm"],
    dateVerified: "2026-09-11",
    notes: "Already registered in CRE_SOURCE_REGISTRY as `bls-ppi-construction` for national PPI construction indices; BLS data is U.S. public domain. Not implemented as an adapter in Phase 7 (deferred) but a natural next candidate given the existing registry entry.",
  },
  {
    sourceId: "hud-user",
    officialName: "U.S. Department of Housing and Urban Development (HUD)",
    country: "US",
    jurisdiction: "Federal",
    datasetOrApiName: "HUD USER / Fair Market Rents, HUD Open Data",
    categories: ["rental_housing", "demographic"],
    url: "https://www.huduser.gov/portal/dataset/fmr-api.html",
    apiAvailability: "public_api",
    downloadFormats: ["JSON", "CSV", "Excel"],
    authRequirement: "free_api_key",
    pricingModel: "free",
    commercialUseRestriction: "permitted",
    redistributionRestriction: "permitted",
    attributionRequired: true,
    updateFrequency: "annual",
    geographicGranularity: "metro_cbsa",
    historicalDepthNote: "Fair Market Rents published annually by fiscal year; historical FMR tables available for prior years.",
    legallyIncorporable: true,
    licenseTags: ["PUBLIC_GOVERNMENT", "PUBLIC_API", "ATTRIBUTION_REQUIRED", "COMMERCIAL_USE_PERMITTED"],
    refresh: {
      retrievalMechanism: "HUD USER FMR REST API",
      historicalBackfillPossible: true,
      automatedIngestionSafe: true,
    },
    citiesCoveredVerified: [],
    evidenceUrls: ["https://www.huduser.gov/portal/dataset/fmr-api.html"],
    dateVerified: "2026-09-11",
    notes: "Fair Market Rents are a RESIDENTIAL rent-subsidy benchmark set by HUD for voucher programs, not a market rental rate and never a commercial rent or cap rate. Included for completeness of the rental_housing category; not implemented as an adapter.",
  },
  {
    sourceId: "data-gov",
    officialName: "U.S. General Services Administration",
    country: "US",
    jurisdiction: "Federal",
    datasetOrApiName: "data.gov Open Data Catalog",
    categories: ["cre_adjacent_economic", "demographic", "construction_permit", "not_available"],
    url: "https://www.data.gov/",
    apiAvailability: "public_api",
    downloadFormats: ["CSV", "JSON", "via CKAN/data.gov API"],
    authRequirement: "none",
    pricingModel: "free",
    commercialUseRestriction: "permitted",
    redistributionRestriction: "permitted",
    attributionRequired: false,
    updateFrequency: "irregular",
    geographicGranularity: "city_municipal",
    historicalDepthNote: "Varies per underlying dataset; data.gov is a catalog/index, not a single time series.",
    legallyIncorporable: true,
    licenseTags: ["PUBLIC_GOVERNMENT", "PUBLIC_API", "PUBLIC_DOWNLOAD", "COMMERCIAL_USE_PERMITTED"],
    refresh: {
      retrievalMechanism: "data.gov CKAN-based catalog API, routing to individual agency datasets",
      historicalBackfillPossible: true,
      automatedIngestionSafe: true,
    },
    citiesCoveredVerified: [],
    evidenceUrls: ["https://www.data.gov/", "https://www.data.gov/privacy-policy#data_policy"],
    dateVerified: "2026-09-11",
    notes: "Federal U.S. government works are public domain by default (17 U.S.C. §105); data.gov itself is a routing/index layer over the same Census/BLS/BEA/HUD sources assessed individually, not an independent CRE dataset. No direct cap-rate data found.",
  },
  {
    sourceId: "texas-comptroller-permits",
    officialName: "State of Texas / City of Austin & City of Houston",
    country: "US",
    jurisdiction: "Texas (state/municipal)",
    datasetOrApiName: "Austin Open Data Portal & Houston Permitting Data (representative state-level example)",
    categories: ["construction_permit", "property_assessment"],
    url: "https://data.austintexas.gov/",
    apiAvailability: "public_api",
    downloadFormats: ["CSV", "JSON", "Socrata API"],
    authRequirement: "none",
    pricingModel: "free",
    commercialUseRestriction: "permitted",
    redistributionRestriction: "unclear",
    attributionRequired: true,
    updateFrequency: "daily",
    geographicGranularity: "city_municipal",
    historicalDepthNote: "Austin's Socrata-based building-permit dataset covers a multi-year rolling history; exact start date not individually verified in this phase.",
    legallyIncorporable: null,
    licenseTags: ["PUBLIC_GOVERNMENT", "PUBLIC_API", "REDISTRIBUTION_UNCLEAR", "ATTRIBUTION_REQUIRED"],
    refresh: {
      retrievalMechanism: "Socrata Open Data API (SODA)",
      historicalBackfillPossible: true,
      automatedIngestionSafe: true,
    },
    citiesCoveredVerified: ["Austin"],
    evidenceUrls: ["https://data.austintexas.gov/"],
    dateVerified: "2026-09-11",
    notes: "Representative example of a municipal open-data portal (Socrata platform, shared by many US cities). Houston, Miami, Seattle and Phoenix each run separate municipal/county portals with their own terms; not individually inventoried in this phase — treat each as GEOGRAPHY_NOT_COVERED until its own terms are read. Building-permit counts/values are construction-ACTIVITY indicators, never a $/SF cost figure or a cap rate.",
  },
] as const;

export function getPublicSource(sourceId: string): CREPublicSourceProfile | undefined {
  return CRE_PUBLIC_SOURCE_REGISTRY.find((s) => s.sourceId === sourceId);
}

export function listPublicSourcesByCategory(category: CREPublicSourceProfile["categories"][number]): CREPublicSourceProfile[] {
  return CRE_PUBLIC_SOURCE_REGISTRY.filter((s) => s.categories.includes(category));
}

/** Sources whose data may be incorporated without a further legal review. */
export function listLegallyIncorporableSources(): CREPublicSourceProfile[] {
  return CRE_PUBLIC_SOURCE_REGISTRY.filter((s) => s.legallyIncorporable === true);
}

/** Sources flagged as requiring a license/legal review before any use. */
export function listSourcesRequiringLicenseReview(): CREPublicSourceProfile[] {
  return CRE_PUBLIC_SOURCE_REGISTRY.filter((s) => s.legallyIncorporable === null || s.legallyIncorporable === false);
}
